# Generated by Django 4.0.2 on 2022-02-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, upload_to='home/adanov', verbose_name='Картинка'),
        ),
    ]
