# Generated by Django 4.0.2 on 2022-02-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_menu', '0002_alter_food_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(max_length=255, verbose_name='описание блюда'),
        ),
    ]
